/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkgSAM;

import java.awt.Graphics;
import java.awt.Image;
import java.io.File;
import javax.swing.ImageIcon;
import static jdk.nashorn.internal.objects.NativeDebug.getClass;

import java.sql.Connection;
import java.sql.Statement;
import java.sql.PreparedStatement;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author zeroone
 */
public class clsSAM extends javax.swing.JFrame {

    /**
     * Creates new form clsSAM
     */
   
   Connection myConn=null;
   Statement myStatement=null;
   ResultSet myResultSet=null;
   
  
   
   public void CreateConnection(String user,String password) throws ClassNotFoundException
   {
       try
       {
        Class.forName("com.mysql.jdbc.Driver"); 
       myConn=DriverManager.getConnection("jdbc:mysql://localhost:3306/test",user,password);
       
       JOptionPane.showMessageDialog(rootPane,"Successfully Connected to Database: "+myConn.getCatalog());
       }
       catch(SQLException exp)
       {
           JOptionPane.showMessageDialog(rootPane, exp.getMessage());
       }
       
       
   }
   
    public clsSAM() {
    
        initComponents();
       
        try {
            File img1 = new File("src/szic.jpg");
            File img2 = new File("src/tpi.jpg");
            jXImageView1.setImage(img1);
            jXImageView2.setImage(img2);
        } catch(Exception ex)
        { JOptionPane.showMessageDialog(rootPane, ex.getMessage()); }
        
        this.setIconImage(new javax.swing.ImageIcon(getClass().getResource("/iconf.jpg")).getImage());
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        panelLogin = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtUser = new javax.swing.JTextField();
        jLabel42 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        jLabel45 = new javax.swing.JLabel();
        btnConnectDB = new javax.swing.JButton();
        jXImageView1 = new org.jdesktop.swingx.JXImageView();
        javax.swing.JPanel panelAddStudent = new javax.swing.JPanel();
        btnAddStudent = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cmbRollnoAssignment = new javax.swing.JComboBox<>();
        txtShowRollno = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtRollno = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        cmbProgram = new javax.swing.JComboBox<>();
        jLabel30 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtFullName = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtFatherName = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtNIC = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtAddress = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtRegistrationNo = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtSession = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        jXImageView2 = new org.jdesktop.swingx.JXImageView();
        panelAddFees = new javax.swing.JPanel();
        btnAddDues = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        txtRollno_panelFeesDues = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        txtAmount = new javax.swing.JTextField();
        txtFees_Type = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        cmbProgram_panelFeesDues = new javax.swing.JComboBox<>();
        jLabel38 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        cmbSemester = new javax.swing.JComboBox<>();
        jLabel39 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        cmbStatus = new javax.swing.JComboBox<>();
        jLabel40 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jXDatePicker1 = new org.jdesktop.swingx.JXDatePicker();
        txtComments = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        panelSearch = new javax.swing.JPanel();
        btnSearch_panelSearch = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        txtPersonal_id_panelSearch = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        panelUpdate = new javax.swing.JPanel();
        btnUpdate_panelUpdate = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        txtFees_id_panelUpdate = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        cmbStatus_panelUpdate = new javax.swing.JComboBox<>();
        jLabel43 = new javax.swing.JLabel();
        jXDatePicker2 = new org.jdesktop.swingx.JXDatePicker();
        jLabel44 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        panelUnpaidStudent = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableUnpaidStudents = new javax.swing.JTable();
        btnRefresh_panelUnpaidStudent = new javax.swing.JButton();
        panelPaidStudent = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablePaidStudents = new javax.swing.JTable();
        btnRefresh_panelPaidStudent = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Students Accounts Manager");
        setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/iconf.jpg")).getImage());
        setIconImages(null);
        setName("SAM_Frame"); // NOI18N
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jTabbedPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        panelLogin.setBackground(new java.awt.Color(153, 153, 255));

        jPanel5.setBackground(new java.awt.Color(204, 204, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Connecting to Database"));

        jLabel1.setText("User Name:");

        txtUser.setText("waheed");

        jLabel42.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(204, 0, 0));
        jLabel42.setText("*");

        jLabel2.setText("Password:");

        jLabel45.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(204, 0, 0));
        jLabel45.setText("*");

        btnConnectDB.setBackground(new java.awt.Color(204, 204, 255));
        btnConnectDB.setText("Connect to Database");
        btnConnectDB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConnectDBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel42, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(24, 24, 24)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(btnConnectDB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(48, 48, 48))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(txtPassword)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel45, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(16, 16, 16))))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel42))
                .addGap(24, 24, 24)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel45))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addComponent(btnConnectDB, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );

        jXImageView1.setBackground(new java.awt.Color(153, 153, 255));
        jXImageView1.setEditable(false);

        javax.swing.GroupLayout jXImageView1Layout = new javax.swing.GroupLayout(jXImageView1);
        jXImageView1.setLayout(jXImageView1Layout);
        jXImageView1Layout.setHorizontalGroup(
            jXImageView1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 188, Short.MAX_VALUE)
        );
        jXImageView1Layout.setVerticalGroup(
            jXImageView1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelLoginLayout = new javax.swing.GroupLayout(panelLogin);
        panelLogin.setLayout(panelLoginLayout);
        panelLoginLayout.setHorizontalGroup(
            panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLoginLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                .addComponent(jXImageView1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61))
        );
        panelLoginLayout.setVerticalGroup(
            panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLoginLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jXImageView1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(283, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Log in", panelLogin);

        panelAddStudent.setBackground(new java.awt.Color(153, 153, 255));
        panelAddStudent.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        btnAddStudent.setBackground(new java.awt.Color(204, 204, 255));
        btnAddStudent.setText("Add Student");
        btnAddStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddStudentActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Check Last Rollno Assigned"));

        jLabel12.setText("Program:");

        jLabel3.setText("Last Rollno Assigned:");

        cmbRollnoAssignment.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "BCS", "BA" }));
        cmbRollnoAssignment.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        cmbRollnoAssignment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbRollnoAssignmentActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addComponent(cmbRollnoAssignment, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtShowRollno, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbRollnoAssignment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtShowRollno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(204, 204, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("New Student"));

        jLabel4.setText("Roll No:");

        jLabel29.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(204, 0, 0));
        jLabel29.setText("*");

        jLabel11.setText("Program:");

        cmbProgram.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "BCS", "BA" }));

        jLabel30.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(204, 0, 0));
        jLabel30.setText("*");

        jLabel5.setText("Full Name:");

        jLabel33.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(204, 0, 0));
        jLabel33.setText("*");

        jLabel6.setText("Father Name:");

        jLabel7.setText("NIC#:");

        jLabel31.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(204, 0, 0));
        jLabel31.setText("*");

        jLabel8.setText("Address:");

        jLabel9.setText("Registration#:");

        jLabel32.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(204, 0, 0));
        jLabel32.setText("*");

        jLabel10.setText("Session:");

        jLabel34.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(204, 0, 0));
        jLabel34.setText("*");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtRollno, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cmbProgram, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtFatherName, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(txtFullName, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(49, 49, 49))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel7))
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtAddress, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                            .addComponent(txtNIC))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))
                        .addGap(43, 43, 43)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtRegistrationNo)
                            .addComponent(txtSession))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel34))
                        .addGap(50, 50, 50))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtRollno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbProgram, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addGap(10, 10, 10))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel29)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel30)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFullName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel33))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtFatherName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNIC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel31)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRegistrationNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel32)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel34)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10)
                        .addComponent(txtSession, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 12, Short.MAX_VALUE))
        );

        jXImageView2.setBackground(new java.awt.Color(255, 255, 255));
        jXImageView2.setEditable(false);

        javax.swing.GroupLayout jXImageView2Layout = new javax.swing.GroupLayout(jXImageView2);
        jXImageView2.setLayout(jXImageView2Layout);
        jXImageView2Layout.setHorizontalGroup(
            jXImageView2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 240, Short.MAX_VALUE)
        );
        jXImageView2Layout.setVerticalGroup(
            jXImageView2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 180, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelAddStudentLayout = new javax.swing.GroupLayout(panelAddStudent);
        panelAddStudent.setLayout(panelAddStudentLayout);
        panelAddStudentLayout.setHorizontalGroup(
            panelAddStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAddStudentLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelAddStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAddStudent))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(panelAddStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jXImageView2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
        );
        panelAddStudentLayout.setVerticalGroup(
            panelAddStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAddStudentLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelAddStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelAddStudentLayout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addComponent(btnAddStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelAddStudentLayout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(jXImageView2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(156, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Add Student ", panelAddStudent);

        panelAddFees.setBackground(new java.awt.Color(153, 153, 255));

        btnAddDues.setBackground(new java.awt.Color(204, 204, 255));
        btnAddDues.setText("Add Dues");
        btnAddDues.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddDuesActionPerformed(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(204, 204, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("New Dues"));

        jLabel13.setText("Rollno:");

        jLabel35.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(204, 0, 0));
        jLabel35.setText("*");

        jLabel14.setText("Amount:");

        jLabel36.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(204, 0, 0));
        jLabel36.setText("*");

        jLabel15.setText("Fees_Type:");

        jLabel37.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(204, 0, 0));
        jLabel37.setText("*");

        jLabel16.setText("Program:");

        cmbProgram_panelFeesDues.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "BCS", "BA" }));

        jLabel38.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(204, 0, 0));
        jLabel38.setText("*");

        jLabel17.setText("Semester:");

        cmbSemester.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1st", "2nd", "3rd", "4th", "5th", "6th", "7th", "8th" }));

        jLabel39.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(204, 0, 0));
        jLabel39.setText("*");

        jLabel19.setText("Status:");

        cmbStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Unpaid", "Paid" }));

        jLabel40.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(204, 0, 0));
        jLabel40.setText("*");

        jLabel20.setText("Paid On:");

        jXDatePicker1.setLightWeightPopupEnabled(false);

        jLabel18.setText("Any Comments:");

        jLabel41.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(204, 0, 0));
        jLabel41.setText("(Optional) Select Date only if Dues are Paid");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addGap(37, 37, 37)
                                .addComponent(txtRollno_panelFeesDues, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel16))
                                .addGap(13, 13, 13)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtAmount)
                                    .addComponent(txtFees_Type)
                                    .addComponent(cmbProgram_panelFeesDues, 0, 94, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel38, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel17)
                                    .addComponent(jLabel19))
                                .addGap(21, 21, 21)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(cmbStatus, 0, 94, Short.MAX_VALUE)
                                    .addComponent(cmbSemester, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel40, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel39, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel20)
                                .addGap(29, 29, 29)
                                .addComponent(jXDatePicker1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel41, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addGap(18, 18, 18)
                        .addComponent(txtComments, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtRollno_panelFeesDues, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel35))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel36)
                    .addComponent(txtAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFees_Type, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel37))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(cmbProgram_panelFeesDues, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel38))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel39, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel17)
                        .addComponent(cmbSemester, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel40)
                    .addComponent(jLabel19))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(jXDatePicker1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel41))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtComments, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelAddFeesLayout = new javax.swing.GroupLayout(panelAddFees);
        panelAddFees.setLayout(panelAddFeesLayout);
        panelAddFeesLayout.setHorizontalGroup(
            panelAddFeesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAddFeesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAddDues, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );
        panelAddFeesLayout.setVerticalGroup(
            panelAddFeesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAddFeesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelAddFeesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnAddDues, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(151, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Add Fees Dues", panelAddFees);

        panelSearch.setBackground(new java.awt.Color(153, 153, 255));

        btnSearch_panelSearch.setBackground(new java.awt.Color(204, 204, 255));
        btnSearch_panelSearch.setText("Search");
        btnSearch_panelSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearch_panelSearchActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Search Student Personal Inofrmation"));

        jLabel28.setForeground(new java.awt.Color(204, 0, 0));
        jLabel28.setText("*");

        jLabel21.setText("Personal id:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPersonal_id_panelSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPersonal_id_panelSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel28))
                .addContainerGap(51, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelSearchLayout = new javax.swing.GroupLayout(panelSearch);
        panelSearch.setLayout(panelSearchLayout);
        panelSearchLayout.setHorizontalGroup(
            panelSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSearchLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(panelSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSearch_panelSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(361, Short.MAX_VALUE))
        );
        panelSearchLayout.setVerticalGroup(
            panelSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSearchLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(btnSearch_panelSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(323, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Search", panelSearch);

        panelUpdate.setBackground(new java.awt.Color(153, 153, 255));

        btnUpdate_panelUpdate.setBackground(new java.awt.Color(204, 204, 255));
        btnUpdate_panelUpdate.setText("Update");
        btnUpdate_panelUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdate_panelUpdateActionPerformed(evt);
            }
        });

        jPanel6.setBackground(new java.awt.Color(204, 204, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Updating a Due"));

        jLabel26.setForeground(new java.awt.Color(255, 0, 0));
        jLabel26.setText("*");

        jLabel25.setText("Fees id:");

        cmbStatus_panelUpdate.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Paid", "Unpaid" }));

        jLabel43.setText("New Status:");

        jLabel44.setText("Paid on:");

        jLabel27.setForeground(new java.awt.Color(255, 0, 0));
        jLabel27.setText("*");

        jLabel46.setForeground(new java.awt.Color(255, 0, 0));
        jLabel46.setText("*");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel43)
                    .addComponent(jLabel25)
                    .addComponent(jLabel44))
                .addGap(27, 27, 27)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbStatus_panelUpdate, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtFees_id_panelUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(71, 71, 71))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jXDatePicker2, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel46, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFees_id_panelUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26)
                    .addComponent(jLabel25))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbStatus_panelUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel43)
                    .addComponent(jLabel27))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel46)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jXDatePicker2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel44)))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelUpdateLayout = new javax.swing.GroupLayout(panelUpdate);
        panelUpdate.setLayout(panelUpdateLayout);
        panelUpdateLayout.setHorizontalGroup(
            panelUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUpdateLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(panelUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdate_panelUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(318, Short.MAX_VALUE))
        );
        panelUpdateLayout.setVerticalGroup(
            panelUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUpdateLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnUpdate_panelUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(252, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Update", panelUpdate);

        panelUnpaidStudent.setBackground(new java.awt.Color(153, 153, 255));

        tableUnpaidStudents.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(102, 255, 102), null, null));
        tableUnpaidStudents.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Fees id", "Rollno", "Amount", "Fees Type", "Status", "Paid on", "Semester", "Program", "Personal id"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableUnpaidStudents.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tableUnpaidStudents.setCellSelectionEnabled(true);
        tableUnpaidStudents.setRowHeight(20);
        jScrollPane1.setViewportView(tableUnpaidStudents);

        btnRefresh_panelUnpaidStudent.setBackground(new java.awt.Color(204, 204, 255));
        btnRefresh_panelUnpaidStudent.setText("Refresh");
        btnRefresh_panelUnpaidStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefresh_panelUnpaidStudentActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelUnpaidStudentLayout = new javax.swing.GroupLayout(panelUnpaidStudent);
        panelUnpaidStudent.setLayout(panelUnpaidStudentLayout);
        panelUnpaidStudentLayout.setHorizontalGroup(
            panelUnpaidStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUnpaidStudentLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelUnpaidStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
                    .addGroup(panelUnpaidStudentLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnRefresh_panelUnpaidStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        panelUnpaidStudentLayout.setVerticalGroup(
            panelUnpaidStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUnpaidStudentLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(btnRefresh_panelUnpaidStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(233, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Unpaid Students", panelUnpaidStudent);

        panelPaidStudent.setBackground(new java.awt.Color(153, 153, 255));

        tablePaidStudents.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(102, 255, 102), null, null));
        tablePaidStudents.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Fees id", "Rollno", "Amount", "Fees Type", "Status", "Paid on", "Semester", "Program", "Personal id"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablePaidStudents.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tablePaidStudents.setRowHeight(20);
        jScrollPane2.setViewportView(tablePaidStudents);

        btnRefresh_panelPaidStudent.setBackground(new java.awt.Color(204, 204, 255));
        btnRefresh_panelPaidStudent.setText("Refresh");
        btnRefresh_panelPaidStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefresh_panelPaidStudentActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelPaidStudentLayout = new javax.swing.GroupLayout(panelPaidStudent);
        panelPaidStudent.setLayout(panelPaidStudentLayout);
        panelPaidStudentLayout.setHorizontalGroup(
            panelPaidStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPaidStudentLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelPaidStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
                    .addGroup(panelPaidStudentLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnRefresh_panelPaidStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        panelPaidStudentLayout.setVerticalGroup(
            panelPaidStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPaidStudentLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(btnRefresh_panelPaidStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(233, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Paid Students", panelPaidStudent);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 627, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 541, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConnectDBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConnectDBActionPerformed
      String user=txtUser.getText();
      String password=String.valueOf(txtPassword.getPassword());
       try {
           CreateConnection(user,password);
           try {
           myStatement=myConn.createStatement();
          
           }
           catch(SQLException exp)
           {
               JOptionPane.showMessageDialog(rootPane, exp.getMessage());
           }
       } catch (ClassNotFoundException ex) {
           Logger.getLogger(clsSAM.class.getName()).log(Level.SEVERE, null, ex);
       }
    }//GEN-LAST:event_btnConnectDBActionPerformed

    
    private void cmbRollnoAssignmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbRollnoAssignmentActionPerformed
        int BCS=1,BA=2;
    try {
      if(myConn==null) 
      {
        
        JOptionPane.showMessageDialog(rootPane,"Please Connect to the Database first");
    }
    else
    {
       
        if((cmbRollnoAssignment.getSelectedItem()).equals("BCS"))
    {
         try {
             
        myResultSet=myStatement.executeQuery("Select max(rollno) from"
                + " Student where program_id="+BCS);
        while(myResultSet.next())
        {
            txtShowRollno.setText(String.valueOf(myResultSet.getInt(1))); 
        }
    }
    catch(SQLException exp) {
        JOptionPane.showMessageDialog(rootPane, exp.getMessage()); }
   
    }
    else 
    {
        
       try {
        myResultSet=myStatement.executeQuery("Select max(rollno) from"
                + " Student where program_id="+BA);
        while(myResultSet.next())
        {
            txtShowRollno.setText(String.valueOf(myResultSet.getInt(1)));
        }
    }
    catch(SQLException exp) {
        JOptionPane.showMessageDialog(rootPane, exp.getMessage());
    }
       }
        
           
        
    }
    }
    catch(Exception exp)
    {
        JOptionPane.showMessageDialog(rootPane, exp.getMessage());
    }
        
    }//GEN-LAST:event_cmbRollnoAssignmentActionPerformed

    private void btnAddStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddStudentActionPerformed
       if(myConn!=null)
       {
        if(!txtRollno.getText().isEmpty() && !txtFullName.getText().isEmpty()
                && !txtNIC.getText().isEmpty() && !txtRegistrationNo.getText().isEmpty()
                && !txtSession.getText().isEmpty()    ) 
        {
        String Name,FatherName,NIC,Address,RegistrationNo,Session;
       int Rollno,Program_id=0,Semester_id=1,Personal_id=0;
       
      Name=txtFullName.getText();
      FatherName=txtFatherName.getText();
      NIC=txtNIC.getText();
      Address=txtAddress.getText();
      RegistrationNo=txtRegistrationNo.getText();
      Session=txtSession.getText();
      
      Rollno=Integer.parseInt(txtRollno.getText());
      if(cmbProgram.getSelectedItem()=="BCS") {
          Program_id=1;
      }
      else if (cmbProgram.getSelectedItem()=="BA") {
          Program_id=2;
      }
      else 
          JOptionPane.showMessageDialog(rootPane,"Pleas Select The Right Program");
      
      String insertInPersonal_info= "INSERT INTO Personal_info(Name,"
              + "Father_Name,NIC,Address,RegistrationNo,Session)"
              + " VALUES('"+Name+"','"+FatherName+"','"+NIC+"','"
              +Address+"','"+RegistrationNo+"','"+Session+"');";
      
      
      
       try {
       myStatement=myConn.createStatement();
       myStatement.executeUpdate(insertInPersonal_info,Statement.RETURN_GENERATED_KEYS);
       myResultSet=myStatement.getGeneratedKeys(); //To get Personal_id key for the updated row
       if(myResultSet.next())
       {
           Personal_id=myResultSet.getInt(1);
       }
       
       for(Semester_id=1; Semester_id<=8; Semester_id++)
       {
           String insertInStudent = "INSERT INTO Student VALUES("+Rollno+""
              +","+Program_id+","+Semester_id+","+Personal_id+");";
           myStatement.executeUpdate(insertInStudent);
           
       }
       JOptionPane.showMessageDialog(rootPane,"New Record Added :)");
       
       }
       catch(SQLException exp) {
       JOptionPane.showMessageDialog(rootPane,exp.getMessage());
           
       }
        }
        else { 
            JOptionPane.showMessageDialog(rootPane,"Please fill the required fields.");
        }
       }
       
       else { JOptionPane.showMessageDialog(rootPane, "Please Connect"
               + " to the database first"); }
        
        
    }//GEN-LAST:event_btnAddStudentActionPerformed

    private void btnAddDuesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddDuesActionPerformed
       if(myConn!=null) 
       {
           if( !txtRollno_panelFeesDues.getText().isEmpty() 
                   && !txtAmount.getText().isEmpty() 
                   && !txtFees_Type.getText().isEmpty()   ) 
           {
        int Rollno,Semester_id=0,Program_id=0,Amount=0;
       String Fees_Type,Status,Paid_on="",Comments;
       Rollno=Integer.parseInt(txtRollno_panelFeesDues.getText());
            if(cmbSemester.getSelectedItem()=="1st") {
           Semester_id=1; }
       else if(cmbSemester.getSelectedItem()=="2nd") {
           Semester_id=2; }
       else if(cmbSemester.getSelectedItem()=="3rd") {
           Semester_id=3; }
       else if(cmbSemester.getSelectedItem()=="4th") {
           Semester_id=4; }
       else if(cmbSemester.getSelectedItem()=="5th") {
           Semester_id=5; }
       else if(cmbSemester.getSelectedItem()=="6th") {
           Semester_id=6; }
       else if(cmbSemester.getSelectedItem()=="7th") {
           Semester_id=7; }
       else if(cmbSemester.getSelectedItem()=="8th") {
           Semester_id=8; }
       else {
           JOptionPane.showMessageDialog(rootPane, "Error: Semester selection");
       }
      if(cmbProgram_panelFeesDues.getSelectedItem()=="BCS") {
          Program_id=1;
      } 
      else if(cmbProgram_panelFeesDues.getSelectedItem()=="BA") {
          Program_id=2;
      }
      
      Amount=Integer.parseInt(txtAmount.getText());
      Fees_Type=txtFees_Type.getText();
      Status=String.valueOf(cmbStatus.getSelectedItem());
      
      Comments=txtComments.getText();
      
     
      String insertInFeesDues2="INSERT INTO Fees_Dues(Rollno,Semester_id"
              + ",Program_id,Amount,Fees_Type,Status,Comments) "
              + "VALUES("+Rollno+","+Semester_id+","+Program_id+""
              + ","+Amount+",'"+Fees_Type+"','"+Status+"','"+Comments+"');";
      
      try {
           
          myStatement=myConn.createStatement();
          if(cmbStatus.getSelectedItem().equals("Unpaid") && jXDatePicker1.getDate()==null)
          {
              myStatement.executeUpdate(insertInFeesDues2);
              JOptionPane.showMessageDialog(rootPane,"New Unpaid Dues Added.");
          }
          else if(cmbStatus.getSelectedItem().equals("Paid")) {
              DateFormat Dformat = new SimpleDateFormat("yyyy-MM-dd");
              Paid_on=Dformat.format(jXDatePicker1.getDate());
              
               String insertInFeesDues="INSERT INTO Fees_Dues(Rollno,Semester_id"
              + ",Program_id,Amount,Fees_Type,Status,Paid_on,Comments) "
              + "VALUES("+Rollno+","+Semester_id+","+Program_id+""
              + ","+Amount+",'"+Fees_Type+"','"+Status+"','"+Paid_on+"'"
              + ",'"+Comments+"');";
               
              myStatement.executeUpdate(insertInFeesDues);
          JOptionPane.showMessageDialog(rootPane,"New Paid Dues Added.");
          }
          else { JOptionPane.showMessageDialog(rootPane, "Incorrect Fields"); }
      }
      catch(SQLException exp)
      {
          JOptionPane.showMessageDialog(rootPane,exp.getMessage());
      }
       } else {JOptionPane.showMessageDialog(rootPane,"Please fill the required fields.");}
       }
       else { JOptionPane.showMessageDialog(rootPane,"Please Connect to the Database first");
       }
     
       
    }//GEN-LAST:event_btnAddDuesActionPerformed

    private void btnRefresh_panelUnpaidStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefresh_panelUnpaidStudentActionPerformed
        if(myConn!=null)
        {
        tableUnpaidStudents.setShowGrid(true);
        DefaultTableModel tableModel = (DefaultTableModel)tableUnpaidStudents.getModel();
        int no_of_rows=0;
        int Fees_id=0,Rollno=0,Amount=0,Semester_id=0,Personal_id=0;
        String Fees_Type="",Status="",Paid_on="",Program_id="";
        String queryUnpaidStudents="SELECT Fees_id,Fees_Dues.Rollno,Fees_Dues.Amount,"
                + "Fees_Dues.Fees_Type,Fees_Dues.Status,"
                + "Fees_Dues.Paid_on,Fees_Dues.Semester_id,Fees_Dues.Program_id,"
                + "Student.Personal_id FROM Fees_Dues,Student WHERE Fees_Dues.Rollno="
                + "Student.Rollno AND Fees_Dues.Semester_id=Student.Semester_id AND "
                + "Fees_Dues.Program_id=Student.Program_id AND Fees_Dues.Status='Unpaid';";
      
       try {
            myStatement=myConn.createStatement();
            myResultSet=myStatement.executeQuery(queryUnpaidStudents);
          while(myResultSet.next())   //Count no of rows
          {
               ++no_of_rows;
           }
          tableModel.setRowCount(no_of_rows);
          myResultSet=myStatement.executeQuery(queryUnpaidStudents);
          int row=0;
            while(myResultSet.next() && row<=no_of_rows)
            {    
                 Fees_id=myResultSet.getInt("Fees_id");
                 Rollno=myResultSet.getInt("Rollno");
                 Amount=myResultSet.getInt("Amount");
                 Fees_Type=myResultSet.getString("Fees_Type");
                Status=myResultSet.getString("Status");
                Paid_on=String.valueOf(myResultSet.getDate("Paid_on"));
                 Semester_id=myResultSet.getInt("Semester_id") ;
                 Program_id=myResultSet.getInt("Program_id")==1?"BCS":"BA" ;
                 Personal_id=myResultSet.getInt("Personal_id") ;
                              
                             tableUnpaidStudents.setValueAt(Fees_id, row, 0);
                             tableUnpaidStudents.setValueAt(Rollno, row, 1);
                             tableUnpaidStudents.setValueAt(Amount,row,2);
                             tableUnpaidStudents.setValueAt(Fees_Type, row, 3);
                             tableUnpaidStudents.setValueAt(Status, row, 4);
                             tableUnpaidStudents.setValueAt(Paid_on, row, 5);
                             tableUnpaidStudents.setValueAt(Semester_id, row, 6);
                             tableUnpaidStudents.setValueAt(Program_id, row, 7);
                             tableUnpaidStudents.setValueAt(Personal_id, row, 8);
                             row++;
                }
   
        }
        catch(SQLException exp) {
            JOptionPane.showMessageDialog(rootPane, exp.getMessage());
        }  
        }
        else { 
            JOptionPane.showMessageDialog(rootPane, "Please Connect to the Database firs."); 
        }
    }//GEN-LAST:event_btnRefresh_panelUnpaidStudentActionPerformed

    private void btnRefresh_panelPaidStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefresh_panelPaidStudentActionPerformed
        
         if(myConn!=null)
        {
        tablePaidStudents.setShowGrid(true);
        DefaultTableModel tableModel = (DefaultTableModel)tablePaidStudents.getModel();
        int no_of_rows=0;
        int Fees_id=0,Rollno=0,Amount=0,Semester_id=0,Personal_id=0;
        String Fees_Type="",Status="",Paid_on="",Program_id="";
        String queryUnpaidStudents="SELECT Fees_id,Fees_Dues.Rollno,Fees_Dues.Amount,"
                + "Fees_Dues.Fees_Type,Fees_Dues.Status,"
                + "Fees_Dues.Paid_on,Fees_Dues.Semester_id,Fees_Dues.Program_id,"
                + "Student.Personal_id FROM Fees_Dues,Student WHERE Fees_Dues.Rollno="
                + "Student.Rollno AND Fees_Dues.Semester_id=Student.Semester_id AND "
                + "Fees_Dues.Program_id=Student.Program_id AND Fees_Dues.Status='Paid';";
      
       try {
            myStatement=myConn.createStatement();
            myResultSet=myStatement.executeQuery(queryUnpaidStudents);
          while(myResultSet.next())   //Count no of rows
          {
               ++no_of_rows;
           }
          tableModel.setRowCount(no_of_rows);
          myResultSet=myStatement.executeQuery(queryUnpaidStudents);
          int row=0;
            while(myResultSet.next() && row<=no_of_rows)
            { 
                 Fees_id=myResultSet.getInt("Fees_id");
                 Rollno=myResultSet.getInt("Rollno");
                 Amount=myResultSet.getInt("Amount");
                 Fees_Type=myResultSet.getString("Fees_Type");
                Status=myResultSet.getString("Status");
                Paid_on=String.valueOf(myResultSet.getDate("Paid_on"));
                 Semester_id=myResultSet.getInt("Semester_id") ;
                 Program_id=myResultSet.getInt("Program_id")==1?"BCS":"BA" ;
                 Personal_id=myResultSet.getInt("Personal_id") ;
                 
                             tablePaidStudents.setValueAt(Fees_id, row, 0);
                             tablePaidStudents.setValueAt(Rollno, row, 1);
                             tablePaidStudents.setValueAt(Amount,row,2);
                             tablePaidStudents.setValueAt(Fees_Type, row, 3);
                             tablePaidStudents.setValueAt(Status, row, 4);
                             tablePaidStudents.setValueAt(Paid_on, row, 5);
                             tablePaidStudents.setValueAt(Semester_id, row, 6);
                             tablePaidStudents.setValueAt(Program_id, row, 7);
                             tablePaidStudents.setValueAt(Personal_id, row, 8);
                             row++;
                }
   
        }
        catch(SQLException exp) {
            JOptionPane.showMessageDialog(rootPane, exp.getMessage());
        }  
        }
        else { 
            JOptionPane.showMessageDialog(rootPane, "Please Connect to the Database firs."); 
        }
        
        
        
        
        
    }//GEN-LAST:event_btnRefresh_panelPaidStudentActionPerformed

    private void btnSearch_panelSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearch_panelSearchActionPerformed
        
        if(myConn!=null && !txtPersonal_id_panelSearch.getText().isEmpty())
        {
        int Personal_id=Integer.parseInt(txtPersonal_id_panelSearch.getText());
        String queryGetPersonalInfo="Select Personal_id,Name,Father_Name,NIC,"
                + "Address,RegistrationNo,Session FROM Personal_info WHERE "
                + "Personal_id="+Personal_id+";";
        try {
            myStatement=myConn.createStatement();
            myResultSet=myStatement.executeQuery(queryGetPersonalInfo);
            
            
            
            while(myResultSet.next())
            {
                
                String Message="******************************************************************************\n"
           +"*                                                                            \n"
	   +"*  Personal_id:         *      "+myResultSet.getInt("Personal_id")+"\n"             
	   +"*  Name:                    *      "+myResultSet.getString("Name")+"\n"
	   +"*  Father_Name:      *      "+myResultSet.getString("Father_Name")+"\n"
	   +"*  NIC:                        *      "+myResultSet.getString("NIC")+"\n"
	   +"*  Address:                *      "+myResultSet.getString("Address")+"\n"
	   +"*  Registration_No: *      "+myResultSet.getString("RegistrationNo")+"\n"
	   +"*  Session:                *      "+myResultSet.getString("Session")+"\n"
	   +"*****************************************************************************\n";
                
                JOptionPane.showMessageDialog(rootPane, Message, "Student Personal Info",1);
                
                
            }
            
        } catch(SQLException ex)
        {
            JOptionPane.showMessageDialog(rootPane,ex.getMessage());
        } 
    
        } else { 
        JOptionPane.showMessageDialog(rootPane,"Please Connect to the Database first \n"
                + "                 OR                 \n"
                + "Fill the required fields."); 
        }     
    }//GEN-LAST:event_btnSearch_panelSearchActionPerformed

    private void btnUpdate_panelUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdate_panelUpdateActionPerformed
       
        if(myConn!=null && !txtFees_id_panelUpdate.getText().isEmpty())
        {
            int Fees_id;
            String Status,Paid_on;
            
            Fees_id=Integer.parseInt(txtFees_id_panelUpdate.getText());
            Status=(String)cmbStatus_panelUpdate.getSelectedItem();
            DateFormat Dformat =new SimpleDateFormat("yyyy-MM-dd");
            Paid_on=Dformat.format(jXDatePicker2.getDate());
            
            String queryUpdateStatus="UPDATE Fees_Dues SET Status='"+Status+"', "
                    + "Paid_on='"+Paid_on+"' WHERE Fees_id="+Fees_id+";";
            
            try {
                myStatement=myConn.createStatement();
                myStatement.executeUpdate(queryUpdateStatus);
                JOptionPane.showMessageDialog(rootPane, "Dues Record: "+Fees_id+""
                        + " Status Updated!");
            } catch(SQLException ex) {
                
            }
            
            
            
        } else {
            JOptionPane.showMessageDialog(rootPane, "Please Connect to the Database first.\n"
                    + "                  OR                 \n"
                    + "Check if all required fields are filled.");
        }
    }//GEN-LAST:event_btnUpdate_panelUpdateActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
int option=JOptionPane.showConfirmDialog(rootPane,"Are You Sure You Want Exit?","Confirm Action",JOptionPane.YES_NO_OPTION);
       if(option==0) {
           this.dispose();
       }

    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(clsSAM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(clsSAM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(clsSAM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(clsSAM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
        
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new clsSAM().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddDues;
    private javax.swing.JButton btnAddStudent;
    private javax.swing.JButton btnConnectDB;
    private javax.swing.JButton btnRefresh_panelPaidStudent;
    private javax.swing.JButton btnRefresh_panelUnpaidStudent;
    private javax.swing.JButton btnSearch_panelSearch;
    private javax.swing.JButton btnUpdate_panelUpdate;
    private javax.swing.JComboBox<String> cmbProgram;
    private javax.swing.JComboBox<String> cmbProgram_panelFeesDues;
    private javax.swing.JComboBox<String> cmbRollnoAssignment;
    private javax.swing.JComboBox<String> cmbSemester;
    private javax.swing.JComboBox<String> cmbStatus;
    private javax.swing.JComboBox<String> cmbStatus_panelUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private org.jdesktop.swingx.JXDatePicker jXDatePicker1;
    private org.jdesktop.swingx.JXDatePicker jXDatePicker2;
    private org.jdesktop.swingx.JXImageView jXImageView1;
    private org.jdesktop.swingx.JXImageView jXImageView2;
    private javax.swing.JPanel panelAddFees;
    private javax.swing.JPanel panelLogin;
    private javax.swing.JPanel panelPaidStudent;
    private javax.swing.JPanel panelSearch;
    private javax.swing.JPanel panelUnpaidStudent;
    private javax.swing.JPanel panelUpdate;
    private javax.swing.JTable tablePaidStudents;
    private javax.swing.JTable tableUnpaidStudents;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtAmount;
    private javax.swing.JTextField txtComments;
    private javax.swing.JTextField txtFatherName;
    private javax.swing.JTextField txtFees_Type;
    private javax.swing.JTextField txtFees_id_panelUpdate;
    private javax.swing.JTextField txtFullName;
    private javax.swing.JTextField txtNIC;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtPersonal_id_panelSearch;
    private javax.swing.JTextField txtRegistrationNo;
    private javax.swing.JTextField txtRollno;
    private javax.swing.JTextField txtRollno_panelFeesDues;
    private javax.swing.JTextField txtSession;
    private javax.swing.JTextField txtShowRollno;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables
}
